# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a63dd1c376ef7f665100a648b87f5400a9c02af78695f5997a508ded13d0400b43f658699cad15e96b976be68a87abcd0c7bde0107cae3d20ea1d2497f797a2f

test:
  secret_key_base: 228cbab025630a523589ac9510df0c646b768cdc0ecbbf2f47366a164ec8fd101c76ba708c1c18a0e105d982ac3306dfb11f6b0e8b247ce3bf07d390eb772f2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
